name: Development CI Builds

on:
  push:
    ignore-forks: true
    branches: [ develop ]

jobs:
  build-ci:
    if: "github.repository == 'gantry/gantry5'"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: opcache, gd
          tools: composer:v2
          coverage: none
        env:
          COMPOSER_TOKEN: ${{ secrets.GLOBAL_TOKEN }}
      - name: Install packages
        run: |
          sudo apt-get -y update -qq  < /dev/null > /dev/null
          sudo apt-get -y install -qq git zip < /dev/null > /dev/null
      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir -d bin/builder)"
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Build Gantry packages
        run: composer build-dev
      - name: Upload files to S3
        if: success()
        uses: ochanje210/simple-s3-upload-action@v1.0.0
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_ACCESS_KEY_SECURE }}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          SOURCE_DIR: 'dist'
          DEST_DIR: 'nightly'
